spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/shravandb
    username: shravan1229
    password: 12345678
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      settings:
        web-allow-others : true
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: update